In [11]:
from sklearn.model_selection import RepeatedKFold, KFold, ShuffleSplit
import numpy as np

In [3]:
X = np.arange(10)
X = X[:, np.newaxis]
X

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [6]:
for test, train in KFold(n_splits=5, shuffle=False).split(X):
    print(test, train)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [7]:
for test, train in KFold(n_splits=5, shuffle=True).split(X):
    print(test, train)

[0 1 2 3 4 7 8 9] [5 6]
[0 1 2 3 5 6 8 9] [4 7]
[0 3 4 5 6 7 8 9] [1 2]
[1 2 4 5 6 7 8 9] [0 3]
[0 1 2 3 4 5 6 7] [8 9]


In [9]:
for test, train in RepeatedKFold(n_splits=5, n_repeats=2).split(X):
    print(test, train)

[1 3 4 5 6 7 8 9] [0 2]
[0 1 2 5 6 7 8 9] [3 4]
[0 1 2 3 4 5 6 9] [7 8]
[0 2 3 4 5 6 7 8] [1 9]
[0 1 2 3 4 7 8 9] [5 6]
[1 2 3 4 5 6 7 8] [0 9]
[0 1 2 3 5 7 8 9] [4 6]
[0 2 4 5 6 7 8 9] [1 3]
[0 1 3 4 6 7 8 9] [2 5]
[0 1 2 3 4 5 6 9] [7 8]


In [10]:
for test, train in RepeatedKFold(n_splits=2, n_repeats=2).split(X):
    print(test, train)

[0 1 2 5 9] [3 4 6 7 8]
[3 4 6 7 8] [0 1 2 5 9]
[0 3 4 6 8] [1 2 5 7 9]
[1 2 5 7 9] [0 3 4 6 8]


In [13]:
for test, train in ShuffleSplit(test_size=0.5, n_splits=5).split(X):
    print(test, train)

[0 9 6 5 7] [3 8 2 4 1]
[4 7 2 3 1] [0 8 5 9 6]
[4 9 8 0 3] [6 7 5 2 1]
[6 0 4 2 1] [5 3 9 7 8]
[0 4 7 1 3] [6 5 9 2 8]
